# config/config.yaml
prefix: train
dataset: CIFAR-100
nepoch: 10
learning_rate: 0.001
increment: 10
model_name: efficientnet_b0
select_rate: 0.2
population: 50
generation: 10
mutation_rate: 0.8
resume: false
checkpoint_dir: checkpoint
seed: 2023