# config/config.yaml

dataset: MNIST
nepoch: 10
learning_rate: 0.001
increment: 5
model_name: mlp
select_rate: 0.2
population: 50
generation: 40
mutation_rate: 0.8
resume: false
checkpoint_dir: checkpoint
seed: 2023